# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [ ]:
import itertools

li = ['A', 'B', 'C']
combination = itertools.combinations(li, 2)
for comb in combination:
  print(comb)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
inf_text = itertools.cycle(["Python", "is", "fun"])
i = 0
for word in inf_text:
  if i == 10: break
  print(word)
  i += 1

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [2]:
import glob

print(glob.glob('*.py'))

[]


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
html = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser')
p_tags = soup('p')
for tag in p_tags:
  print(tag.contents[0])

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [ ]:
import re

text = "AI is AI. But in linguistics, ai or Ai is not AI."
new_text = re.sub("AI", "Aritificial Intelligence", text)
print(new_text)

Aritificial Intelligence is Aritificial Intelligence. But in linguistics, ai or Ai is not Aritificial Intelligence.


**CP6**: Create a numpy array of 10 zeros.

In [ ]:
import numpy as np

print(np.zeros([2, 5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**CP7** Create a numpy array of the integers from 10 to 49.

In [ ]:
start, end = 10, 49
print(np.arange(start, end+1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [ ]:
start, end = 0, 8
print(np.arange(start, end+1).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

### Answer
The reason why machine learning models require such a large amount of data is mainly due to the fact the precision and accuracy of the model heavily depends on the amount of data that it's being fed. It also helps to avoid the inconsisitencies in the model by reducing generalization and overfitting.

When we label a data as big, we refer to the following three properties of data.
- Velocity: the speed at which data is created and collected
- Veractiy: the variety of the format of how data collected
- Volume: the amount of data that is being collected.

#### Conclusion: We call amount of data large, when the volume of the data that we are gonna process is in big quantity.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

### Answer

There are challenges that come with the rise of AI driven world. Some of them are,

1. Autonomous weapons: AI can be used to power weaponery technology.
2. Deepfakes: AI can be used to fabricate fake images and videos that could be used to leave false impressions and could lead up to further damage.

**The Solution:** possible solutions are to introduce the ethical guidelines, through open dialogue and public engagement.